### ISSUE TITLE
Full of bugs

### ISSUE THREAD

**Issue by brucealthompson** [saitho/git-file-webserver#4]
I am debugging this program as it is full of bugs. The idea is good. The implementation is not.

**Comment by saitho** [comment]
Hey there,
welcome to GitHub.

Feel free to make changes to the source code and contribute them. Or create your own solution that works better. :)

**Comment by brucealthompson** [comment]
The issues were all in the windows version. I build the trunk for linux and it seems to work.

 

               Bruce T
